const minimum = 1;
const maximum = 100;

const num = Math.floor(Math.random() * (maximum - minimum + 1)) + minimum;

// In this exercise, you will need to work out what num represents?
// Try breaking down the expression and using documentation to explain what it means
// It will help to think about the order in which expressions are evaluated
// Try logging the value of num and running the program several times to build an idea of what the program is doing

num //represents a random integer between the minimum value (1) and the maximum value (100).Math

(maximum - minimum + 1) //represents the range of possible values, which is 100 - 1 + 1 = 100. 
// This means that there are 100 possible values that num can take on.

Math.random() //generates a random decimal number between 0  and 1. This means that the value of Math.random() 
// can be any number between 0 and 1, but it will never be exactly 1.

Math.floor(Math.random() * (maximum - minimum + 1)) //multiplies the random decimal number generated by Math.random() 
// by the range of possible values (100), and then rounds down to the nearest integer using Math.floor(). 
// This means that the result will be a random integer between 0 and 99.

Math.floor(Math.random() * (maximum - minimum + 1)) + minimum //adds the minimum value (1) to the result of the previous 
// expression. This means that the final result will be a random integer between 1 and 100, inclusive.



