const minimum = 1;
const maximum = 100;

const num = Math.floor(Math.random() * (maximum - minimum + 1)) + minimum;

// In this exercise, you will need to work out what num represents?
// Try breaking down the expression and using documentation to explain what it means
// It will help to think about the order in which expressions are evaluated
// Try logging the value of num and running the program several times to build an idea of what the program is doing
//console.log(num)
//output: random whole number

//So num is storing the value of a random number generated by the method Math.random this will be a decimal number between zero and one that is then multiplied by 100 (100(maximum) -1(minimum) +1) and then the Math.floor method will round that number down to the nearest whole number and then finally whatever this number is, one is added on to that number and this final number is what is stored in the variable num. This final number is what is stored in the variable num. The smallest value it can be is 1, and the largest value it can be is 100 as plus minimum means 1 will always be added.

//example Math.random () = 0.97
//0.97 * 100 = 97
//Math.floor = 97
//97+1 = 98
