const minimum = 1;
const maximum = 100;

const num = Math.floor(Math.random() * (maximum - minimum + 1)) + minimum;

// In this exercise, you will need to work out what num represents?
// Try breaking down the expression and using documentation to explain what it means
// It will help to think about the order in which expressions are evaluated
// Try logging the value of num and running the program several times to build an idea of what the program is doing

// num represents a variable. The expression assign a value to this variable.
// Math.floor () and Math.random () are methods.
// The value inside Math.floor() is its argument. The return value of this argument is expression within the yellow parenthesis.
// The whole expression of variable "num" is that a float generated by method Math.random() is multiplied by return value of the range specified by value between declared variable by key word constant.
// The method Math.floor() then return greatest integer of the value of this product.
// And finally plus the value of minimum variable declared.

//`num` is a random integer between maximum and minimum inclusive.
// The smallest value of 'num' can be 1

console.log(num);
